### ISSUE TITLE
Mostrar en la gráfica de tiempo salto cuando no hay datos

### ISSUE THREAD

**Issue by anattolia** [enflujo/imagina-maternoinfantil#11]
Si no hay datos en uno o varios años, hacerlo evidente en la gráfica de tiempo con un salto o una marca visual.

**Comment by 1cgonza** [comment]
También en el menú de años

**Comment by 1cgonza** [comment]
Arreglado en 32c96a0ebe53dd7a7684ca60d1fb418196bb7fce y d5a76f37bb34ea38483f0650ce75cfddd6b08a45
