### ISSUE TITLE
(Linea de tiempo) implementar cambio de cortes cuando no es proporción

### ISSUE THREAD

**Issue by 1cgonza** [enflujo/imagina-maternoinfantil#36]
Ahora sólo hacemos cortes de 0 a 100%, para los indicadores que no son porcentaje toca definir el máximo y crear lo cortes dependiendo del indicador seleccionado.

**Comment by anattolia** [comment]
Sugiero lo que habíamos hablado: buscar el máximo en todos los valores de ese indicador (quizás excluyendo "lugar desconocido") y redondear hacia arriba.

Los cortes podrían ser ese valor / 5. ¿Raro?

**Comment by 1cgonza** [comment]
> Sugiero lo que habíamos hablado: buscar el máximo en todos los valores de ese indicador (quizás excluyendo "lugar desconocido") y redondear hacia arriba.
> 
> Los cortes podrían ser ese valor / 5. ¿Raro?

Me parece bien!
